/*
cardano-node-api

Testing LocaltxsubmissionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/blinklabs-io/cardano-node-api/openapi"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_LocaltxsubmissionAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run(
		"Test LocaltxsubmissionAPIService LocaltxsubmissionTxPost",
		func(t *testing.T) {

			t.Skip("skip test") // remove to run test

			resp, httpRes, err := apiClient.LocaltxsubmissionAPI.LocaltxsubmissionTxPost(context.Background()).
				Execute()

			require.Nil(t, err)
			require.NotNil(t, resp)
			assert.Equal(t, 200, httpRes.StatusCode)

		},
	)

}
