/*
cardano-node-api

Cardano Node API

API version: 1.0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiResponseLocalTxMonitorTxs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiResponseLocalTxMonitorTxs{}

// ApiResponseLocalTxMonitorTxs struct for ApiResponseLocalTxMonitorTxs
type ApiResponseLocalTxMonitorTxs struct {
	TxBytes *string `json:"tx_bytes,omitempty"`
	TxHash *string `json:"tx_hash,omitempty"`
}

// NewApiResponseLocalTxMonitorTxs instantiates a new ApiResponseLocalTxMonitorTxs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiResponseLocalTxMonitorTxs() *ApiResponseLocalTxMonitorTxs {
	this := ApiResponseLocalTxMonitorTxs{}
	return &this
}

// NewApiResponseLocalTxMonitorTxsWithDefaults instantiates a new ApiResponseLocalTxMonitorTxs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiResponseLocalTxMonitorTxsWithDefaults() *ApiResponseLocalTxMonitorTxs {
	this := ApiResponseLocalTxMonitorTxs{}
	return &this
}

// GetTxBytes returns the TxBytes field value if set, zero value otherwise.
func (o *ApiResponseLocalTxMonitorTxs) GetTxBytes() string {
	if o == nil || IsNil(o.TxBytes) {
		var ret string
		return ret
	}
	return *o.TxBytes
}

// GetTxBytesOk returns a tuple with the TxBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseLocalTxMonitorTxs) GetTxBytesOk() (*string, bool) {
	if o == nil || IsNil(o.TxBytes) {
		return nil, false
	}
	return o.TxBytes, true
}

// HasTxBytes returns a boolean if a field has been set.
func (o *ApiResponseLocalTxMonitorTxs) HasTxBytes() bool {
	if o != nil && !IsNil(o.TxBytes) {
		return true
	}

	return false
}

// SetTxBytes gets a reference to the given string and assigns it to the TxBytes field.
func (o *ApiResponseLocalTxMonitorTxs) SetTxBytes(v string) {
	o.TxBytes = &v
}

// GetTxHash returns the TxHash field value if set, zero value otherwise.
func (o *ApiResponseLocalTxMonitorTxs) GetTxHash() string {
	if o == nil || IsNil(o.TxHash) {
		var ret string
		return ret
	}
	return *o.TxHash
}

// GetTxHashOk returns a tuple with the TxHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseLocalTxMonitorTxs) GetTxHashOk() (*string, bool) {
	if o == nil || IsNil(o.TxHash) {
		return nil, false
	}
	return o.TxHash, true
}

// HasTxHash returns a boolean if a field has been set.
func (o *ApiResponseLocalTxMonitorTxs) HasTxHash() bool {
	if o != nil && !IsNil(o.TxHash) {
		return true
	}

	return false
}

// SetTxHash gets a reference to the given string and assigns it to the TxHash field.
func (o *ApiResponseLocalTxMonitorTxs) SetTxHash(v string) {
	o.TxHash = &v
}

func (o ApiResponseLocalTxMonitorTxs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiResponseLocalTxMonitorTxs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TxBytes) {
		toSerialize["tx_bytes"] = o.TxBytes
	}
	if !IsNil(o.TxHash) {
		toSerialize["tx_hash"] = o.TxHash
	}
	return toSerialize, nil
}

type NullableApiResponseLocalTxMonitorTxs struct {
	value *ApiResponseLocalTxMonitorTxs
	isSet bool
}

func (v NullableApiResponseLocalTxMonitorTxs) Get() *ApiResponseLocalTxMonitorTxs {
	return v.value
}

func (v *NullableApiResponseLocalTxMonitorTxs) Set(val *ApiResponseLocalTxMonitorTxs) {
	v.value = val
	v.isSet = true
}

func (v NullableApiResponseLocalTxMonitorTxs) IsSet() bool {
	return v.isSet
}

func (v *NullableApiResponseLocalTxMonitorTxs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiResponseLocalTxMonitorTxs(val *ApiResponseLocalTxMonitorTxs) *NullableApiResponseLocalTxMonitorTxs {
	return &NullableApiResponseLocalTxMonitorTxs{value: val, isSet: true}
}

func (v NullableApiResponseLocalTxMonitorTxs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiResponseLocalTxMonitorTxs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


