/*
cardano-node-api

Cardano Node API

API version: 1.0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiResponseLocalStateQueryCurrentEra type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiResponseLocalStateQueryCurrentEra{}

// ApiResponseLocalStateQueryCurrentEra struct for ApiResponseLocalStateQueryCurrentEra
type ApiResponseLocalStateQueryCurrentEra struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewApiResponseLocalStateQueryCurrentEra instantiates a new ApiResponseLocalStateQueryCurrentEra object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiResponseLocalStateQueryCurrentEra() *ApiResponseLocalStateQueryCurrentEra {
	this := ApiResponseLocalStateQueryCurrentEra{}
	return &this
}

// NewApiResponseLocalStateQueryCurrentEraWithDefaults instantiates a new ApiResponseLocalStateQueryCurrentEra object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiResponseLocalStateQueryCurrentEraWithDefaults() *ApiResponseLocalStateQueryCurrentEra {
	this := ApiResponseLocalStateQueryCurrentEra{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApiResponseLocalStateQueryCurrentEra) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseLocalStateQueryCurrentEra) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApiResponseLocalStateQueryCurrentEra) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ApiResponseLocalStateQueryCurrentEra) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApiResponseLocalStateQueryCurrentEra) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseLocalStateQueryCurrentEra) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApiResponseLocalStateQueryCurrentEra) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApiResponseLocalStateQueryCurrentEra) SetName(v string) {
	o.Name = &v
}

func (o ApiResponseLocalStateQueryCurrentEra) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiResponseLocalStateQueryCurrentEra) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableApiResponseLocalStateQueryCurrentEra struct {
	value *ApiResponseLocalStateQueryCurrentEra
	isSet bool
}

func (v NullableApiResponseLocalStateQueryCurrentEra) Get() *ApiResponseLocalStateQueryCurrentEra {
	return v.value
}

func (v *NullableApiResponseLocalStateQueryCurrentEra) Set(val *ApiResponseLocalStateQueryCurrentEra) {
	v.value = val
	v.isSet = true
}

func (v NullableApiResponseLocalStateQueryCurrentEra) IsSet() bool {
	return v.isSet
}

func (v *NullableApiResponseLocalStateQueryCurrentEra) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiResponseLocalStateQueryCurrentEra(val *ApiResponseLocalStateQueryCurrentEra) *NullableApiResponseLocalStateQueryCurrentEra {
	return &NullableApiResponseLocalStateQueryCurrentEra{value: val, isSet: true}
}

func (v NullableApiResponseLocalStateQueryCurrentEra) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiResponseLocalStateQueryCurrentEra) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


