/*
cardano-node-api

Cardano Node API

API version: 1.0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiResponseLocalTxMonitorHasTx type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiResponseLocalTxMonitorHasTx{}

// ApiResponseLocalTxMonitorHasTx struct for ApiResponseLocalTxMonitorHasTx
type ApiResponseLocalTxMonitorHasTx struct {
	HasTx *bool `json:"has_tx,omitempty"`
}

// NewApiResponseLocalTxMonitorHasTx instantiates a new ApiResponseLocalTxMonitorHasTx object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiResponseLocalTxMonitorHasTx() *ApiResponseLocalTxMonitorHasTx {
	this := ApiResponseLocalTxMonitorHasTx{}
	return &this
}

// NewApiResponseLocalTxMonitorHasTxWithDefaults instantiates a new ApiResponseLocalTxMonitorHasTx object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiResponseLocalTxMonitorHasTxWithDefaults() *ApiResponseLocalTxMonitorHasTx {
	this := ApiResponseLocalTxMonitorHasTx{}
	return &this
}

// GetHasTx returns the HasTx field value if set, zero value otherwise.
func (o *ApiResponseLocalTxMonitorHasTx) GetHasTx() bool {
	if o == nil || IsNil(o.HasTx) {
		var ret bool
		return ret
	}
	return *o.HasTx
}

// GetHasTxOk returns a tuple with the HasTx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseLocalTxMonitorHasTx) GetHasTxOk() (*bool, bool) {
	if o == nil || IsNil(o.HasTx) {
		return nil, false
	}
	return o.HasTx, true
}

// HasHasTx returns a boolean if a field has been set.
func (o *ApiResponseLocalTxMonitorHasTx) HasHasTx() bool {
	if o != nil && !IsNil(o.HasTx) {
		return true
	}

	return false
}

// SetHasTx gets a reference to the given bool and assigns it to the HasTx field.
func (o *ApiResponseLocalTxMonitorHasTx) SetHasTx(v bool) {
	o.HasTx = &v
}

func (o ApiResponseLocalTxMonitorHasTx) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiResponseLocalTxMonitorHasTx) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HasTx) {
		toSerialize["has_tx"] = o.HasTx
	}
	return toSerialize, nil
}

type NullableApiResponseLocalTxMonitorHasTx struct {
	value *ApiResponseLocalTxMonitorHasTx
	isSet bool
}

func (v NullableApiResponseLocalTxMonitorHasTx) Get() *ApiResponseLocalTxMonitorHasTx {
	return v.value
}

func (v *NullableApiResponseLocalTxMonitorHasTx) Set(val *ApiResponseLocalTxMonitorHasTx) {
	v.value = val
	v.isSet = true
}

func (v NullableApiResponseLocalTxMonitorHasTx) IsSet() bool {
	return v.isSet
}

func (v *NullableApiResponseLocalTxMonitorHasTx) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiResponseLocalTxMonitorHasTx(val *ApiResponseLocalTxMonitorHasTx) *NullableApiResponseLocalTxMonitorHasTx {
	return &NullableApiResponseLocalTxMonitorHasTx{value: val, isSet: true}
}

func (v NullableApiResponseLocalTxMonitorHasTx) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiResponseLocalTxMonitorHasTx) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


