/*
cardano-node-api

Cardano Node API

API version: 1.0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiResponseLocalStateQueryTip type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiResponseLocalStateQueryTip{}

// ApiResponseLocalStateQueryTip struct for ApiResponseLocalStateQueryTip
type ApiResponseLocalStateQueryTip struct {
	BlockNo *int32  `json:"block_no,omitempty"`
	EpochNo *int32  `json:"epoch_no,omitempty"`
	Era     *string `json:"era,omitempty"`
	Hash    *string `json:"hash,omitempty"`
	SlotNo  *int32  `json:"slot_no,omitempty"`
}

// NewApiResponseLocalStateQueryTip instantiates a new ApiResponseLocalStateQueryTip object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiResponseLocalStateQueryTip() *ApiResponseLocalStateQueryTip {
	this := ApiResponseLocalStateQueryTip{}
	return &this
}

// NewApiResponseLocalStateQueryTipWithDefaults instantiates a new ApiResponseLocalStateQueryTip object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiResponseLocalStateQueryTipWithDefaults() *ApiResponseLocalStateQueryTip {
	this := ApiResponseLocalStateQueryTip{}
	return &this
}

// GetBlockNo returns the BlockNo field value if set, zero value otherwise.
func (o *ApiResponseLocalStateQueryTip) GetBlockNo() int32 {
	if o == nil || IsNil(o.BlockNo) {
		var ret int32
		return ret
	}
	return *o.BlockNo
}

// GetBlockNoOk returns a tuple with the BlockNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseLocalStateQueryTip) GetBlockNoOk() (*int32, bool) {
	if o == nil || IsNil(o.BlockNo) {
		return nil, false
	}
	return o.BlockNo, true
}

// HasBlockNo returns a boolean if a field has been set.
func (o *ApiResponseLocalStateQueryTip) HasBlockNo() bool {
	if o != nil && !IsNil(o.BlockNo) {
		return true
	}

	return false
}

// SetBlockNo gets a reference to the given int32 and assigns it to the BlockNo field.
func (o *ApiResponseLocalStateQueryTip) SetBlockNo(v int32) {
	o.BlockNo = &v
}

// GetEpochNo returns the EpochNo field value if set, zero value otherwise.
func (o *ApiResponseLocalStateQueryTip) GetEpochNo() int32 {
	if o == nil || IsNil(o.EpochNo) {
		var ret int32
		return ret
	}
	return *o.EpochNo
}

// GetEpochNoOk returns a tuple with the EpochNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseLocalStateQueryTip) GetEpochNoOk() (*int32, bool) {
	if o == nil || IsNil(o.EpochNo) {
		return nil, false
	}
	return o.EpochNo, true
}

// HasEpochNo returns a boolean if a field has been set.
func (o *ApiResponseLocalStateQueryTip) HasEpochNo() bool {
	if o != nil && !IsNil(o.EpochNo) {
		return true
	}

	return false
}

// SetEpochNo gets a reference to the given int32 and assigns it to the EpochNo field.
func (o *ApiResponseLocalStateQueryTip) SetEpochNo(v int32) {
	o.EpochNo = &v
}

// GetEra returns the Era field value if set, zero value otherwise.
func (o *ApiResponseLocalStateQueryTip) GetEra() string {
	if o == nil || IsNil(o.Era) {
		var ret string
		return ret
	}
	return *o.Era
}

// GetEraOk returns a tuple with the Era field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseLocalStateQueryTip) GetEraOk() (*string, bool) {
	if o == nil || IsNil(o.Era) {
		return nil, false
	}
	return o.Era, true
}

// HasEra returns a boolean if a field has been set.
func (o *ApiResponseLocalStateQueryTip) HasEra() bool {
	if o != nil && !IsNil(o.Era) {
		return true
	}

	return false
}

// SetEra gets a reference to the given string and assigns it to the Era field.
func (o *ApiResponseLocalStateQueryTip) SetEra(v string) {
	o.Era = &v
}

// GetHash returns the Hash field value if set, zero value otherwise.
func (o *ApiResponseLocalStateQueryTip) GetHash() string {
	if o == nil || IsNil(o.Hash) {
		var ret string
		return ret
	}
	return *o.Hash
}

// GetHashOk returns a tuple with the Hash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseLocalStateQueryTip) GetHashOk() (*string, bool) {
	if o == nil || IsNil(o.Hash) {
		return nil, false
	}
	return o.Hash, true
}

// HasHash returns a boolean if a field has been set.
func (o *ApiResponseLocalStateQueryTip) HasHash() bool {
	if o != nil && !IsNil(o.Hash) {
		return true
	}

	return false
}

// SetHash gets a reference to the given string and assigns it to the Hash field.
func (o *ApiResponseLocalStateQueryTip) SetHash(v string) {
	o.Hash = &v
}

// GetSlotNo returns the SlotNo field value if set, zero value otherwise.
func (o *ApiResponseLocalStateQueryTip) GetSlotNo() int32 {
	if o == nil || IsNil(o.SlotNo) {
		var ret int32
		return ret
	}
	return *o.SlotNo
}

// GetSlotNoOk returns a tuple with the SlotNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseLocalStateQueryTip) GetSlotNoOk() (*int32, bool) {
	if o == nil || IsNil(o.SlotNo) {
		return nil, false
	}
	return o.SlotNo, true
}

// HasSlotNo returns a boolean if a field has been set.
func (o *ApiResponseLocalStateQueryTip) HasSlotNo() bool {
	if o != nil && !IsNil(o.SlotNo) {
		return true
	}

	return false
}

// SetSlotNo gets a reference to the given int32 and assigns it to the SlotNo field.
func (o *ApiResponseLocalStateQueryTip) SetSlotNo(v int32) {
	o.SlotNo = &v
}

func (o ApiResponseLocalStateQueryTip) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiResponseLocalStateQueryTip) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BlockNo) {
		toSerialize["block_no"] = o.BlockNo
	}
	if !IsNil(o.EpochNo) {
		toSerialize["epoch_no"] = o.EpochNo
	}
	if !IsNil(o.Era) {
		toSerialize["era"] = o.Era
	}
	if !IsNil(o.Hash) {
		toSerialize["hash"] = o.Hash
	}
	if !IsNil(o.SlotNo) {
		toSerialize["slot_no"] = o.SlotNo
	}
	return toSerialize, nil
}

type NullableApiResponseLocalStateQueryTip struct {
	value *ApiResponseLocalStateQueryTip
	isSet bool
}

func (v NullableApiResponseLocalStateQueryTip) Get() *ApiResponseLocalStateQueryTip {
	return v.value
}

func (v *NullableApiResponseLocalStateQueryTip) Set(
	val *ApiResponseLocalStateQueryTip,
) {
	v.value = val
	v.isSet = true
}

func (v NullableApiResponseLocalStateQueryTip) IsSet() bool {
	return v.isSet
}

func (v *NullableApiResponseLocalStateQueryTip) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiResponseLocalStateQueryTip(
	val *ApiResponseLocalStateQueryTip,
) *NullableApiResponseLocalStateQueryTip {
	return &NullableApiResponseLocalStateQueryTip{value: val, isSet: true}
}

func (v NullableApiResponseLocalStateQueryTip) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiResponseLocalStateQueryTip) UnmarshalJSON(
	src []byte,
) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
