/*
cardano-node-api

Cardano Node API

API version: 1.0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiResponseLocalStateQuerySearchUTxOsByAsset type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiResponseLocalStateQuerySearchUTxOsByAsset{}

// ApiResponseLocalStateQuerySearchUTxOsByAsset struct for ApiResponseLocalStateQuerySearchUTxOsByAsset
type ApiResponseLocalStateQuerySearchUTxOsByAsset struct {
	Count *int32        `json:"count,omitempty"`
	Utxos []ApiUtxoItem `json:"utxos,omitempty"`
}

// NewApiResponseLocalStateQuerySearchUTxOsByAsset instantiates a new ApiResponseLocalStateQuerySearchUTxOsByAsset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiResponseLocalStateQuerySearchUTxOsByAsset() *ApiResponseLocalStateQuerySearchUTxOsByAsset {
	this := ApiResponseLocalStateQuerySearchUTxOsByAsset{}
	return &this
}

// NewApiResponseLocalStateQuerySearchUTxOsByAssetWithDefaults instantiates a new ApiResponseLocalStateQuerySearchUTxOsByAsset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiResponseLocalStateQuerySearchUTxOsByAssetWithDefaults() *ApiResponseLocalStateQuerySearchUTxOsByAsset {
	this := ApiResponseLocalStateQuerySearchUTxOsByAsset{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ApiResponseLocalStateQuerySearchUTxOsByAsset) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseLocalStateQuerySearchUTxOsByAsset) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ApiResponseLocalStateQuerySearchUTxOsByAsset) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *ApiResponseLocalStateQuerySearchUTxOsByAsset) SetCount(v int32) {
	o.Count = &v
}

// GetUtxos returns the Utxos field value if set, zero value otherwise.
func (o *ApiResponseLocalStateQuerySearchUTxOsByAsset) GetUtxos() []ApiUtxoItem {
	if o == nil || IsNil(o.Utxos) {
		var ret []ApiUtxoItem
		return ret
	}
	return o.Utxos
}

// GetUtxosOk returns a tuple with the Utxos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseLocalStateQuerySearchUTxOsByAsset) GetUtxosOk() ([]ApiUtxoItem, bool) {
	if o == nil || IsNil(o.Utxos) {
		return nil, false
	}
	return o.Utxos, true
}

// HasUtxos returns a boolean if a field has been set.
func (o *ApiResponseLocalStateQuerySearchUTxOsByAsset) HasUtxos() bool {
	if o != nil && !IsNil(o.Utxos) {
		return true
	}

	return false
}

// SetUtxos gets a reference to the given []ApiUtxoItem and assigns it to the Utxos field.
func (o *ApiResponseLocalStateQuerySearchUTxOsByAsset) SetUtxos(
	v []ApiUtxoItem,
) {
	o.Utxos = v
}

func (o ApiResponseLocalStateQuerySearchUTxOsByAsset) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiResponseLocalStateQuerySearchUTxOsByAsset) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Utxos) {
		toSerialize["utxos"] = o.Utxos
	}
	return toSerialize, nil
}

type NullableApiResponseLocalStateQuerySearchUTxOsByAsset struct {
	value *ApiResponseLocalStateQuerySearchUTxOsByAsset
	isSet bool
}

func (v NullableApiResponseLocalStateQuerySearchUTxOsByAsset) Get() *ApiResponseLocalStateQuerySearchUTxOsByAsset {
	return v.value
}

func (v *NullableApiResponseLocalStateQuerySearchUTxOsByAsset) Set(
	val *ApiResponseLocalStateQuerySearchUTxOsByAsset,
) {
	v.value = val
	v.isSet = true
}

func (v NullableApiResponseLocalStateQuerySearchUTxOsByAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableApiResponseLocalStateQuerySearchUTxOsByAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiResponseLocalStateQuerySearchUTxOsByAsset(
	val *ApiResponseLocalStateQuerySearchUTxOsByAsset,
) *NullableApiResponseLocalStateQuerySearchUTxOsByAsset {
	return &NullableApiResponseLocalStateQuerySearchUTxOsByAsset{
		value: val,
		isSet: true,
	}
}

func (v NullableApiResponseLocalStateQuerySearchUTxOsByAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiResponseLocalStateQuerySearchUTxOsByAsset) UnmarshalJSON(
	src []byte,
) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
