/*
cardano-node-api

Cardano Node API

API version: 1.0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiUtxoItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiUtxoItem{}

// ApiUtxoItem struct for ApiUtxoItem
type ApiUtxoItem struct {
	Address *string                `json:"address,omitempty"`
	Amount  *int64                 `json:"amount,omitempty"`
	Assets  map[string]interface{} `json:"assets,omitempty"`
	Index   *int32                 `json:"index,omitempty"`
	TxHash  *string                `json:"tx_hash,omitempty"`
}

// NewApiUtxoItem instantiates a new ApiUtxoItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiUtxoItem() *ApiUtxoItem {
	this := ApiUtxoItem{}
	return &this
}

// NewApiUtxoItemWithDefaults instantiates a new ApiUtxoItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiUtxoItemWithDefaults() *ApiUtxoItem {
	this := ApiUtxoItem{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *ApiUtxoItem) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiUtxoItem) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *ApiUtxoItem) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *ApiUtxoItem) SetAddress(v string) {
	o.Address = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ApiUtxoItem) GetAmount() int64 {
	if o == nil || IsNil(o.Amount) {
		var ret int64
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiUtxoItem) GetAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ApiUtxoItem) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int64 and assigns it to the Amount field.
func (o *ApiUtxoItem) SetAmount(v int64) {
	o.Amount = &v
}

// GetAssets returns the Assets field value if set, zero value otherwise.
func (o *ApiUtxoItem) GetAssets() map[string]interface{} {
	if o == nil || IsNil(o.Assets) {
		var ret map[string]interface{}
		return ret
	}
	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiUtxoItem) GetAssetsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Assets) {
		return map[string]interface{}{}, false
	}
	return o.Assets, true
}

// HasAssets returns a boolean if a field has been set.
func (o *ApiUtxoItem) HasAssets() bool {
	if o != nil && !IsNil(o.Assets) {
		return true
	}

	return false
}

// SetAssets gets a reference to the given map[string]interface{} and assigns it to the Assets field.
func (o *ApiUtxoItem) SetAssets(v map[string]interface{}) {
	o.Assets = v
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *ApiUtxoItem) GetIndex() int32 {
	if o == nil || IsNil(o.Index) {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiUtxoItem) GetIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *ApiUtxoItem) HasIndex() bool {
	if o != nil && !IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *ApiUtxoItem) SetIndex(v int32) {
	o.Index = &v
}

// GetTxHash returns the TxHash field value if set, zero value otherwise.
func (o *ApiUtxoItem) GetTxHash() string {
	if o == nil || IsNil(o.TxHash) {
		var ret string
		return ret
	}
	return *o.TxHash
}

// GetTxHashOk returns a tuple with the TxHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiUtxoItem) GetTxHashOk() (*string, bool) {
	if o == nil || IsNil(o.TxHash) {
		return nil, false
	}
	return o.TxHash, true
}

// HasTxHash returns a boolean if a field has been set.
func (o *ApiUtxoItem) HasTxHash() bool {
	if o != nil && !IsNil(o.TxHash) {
		return true
	}

	return false
}

// SetTxHash gets a reference to the given string and assigns it to the TxHash field.
func (o *ApiUtxoItem) SetTxHash(v string) {
	o.TxHash = &v
}

func (o ApiUtxoItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiUtxoItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Assets) {
		toSerialize["assets"] = o.Assets
	}
	if !IsNil(o.Index) {
		toSerialize["index"] = o.Index
	}
	if !IsNil(o.TxHash) {
		toSerialize["tx_hash"] = o.TxHash
	}
	return toSerialize, nil
}

type NullableApiUtxoItem struct {
	value *ApiUtxoItem
	isSet bool
}

func (v NullableApiUtxoItem) Get() *ApiUtxoItem {
	return v.value
}

func (v *NullableApiUtxoItem) Set(val *ApiUtxoItem) {
	v.value = val
	v.isSet = true
}

func (v NullableApiUtxoItem) IsSet() bool {
	return v.isSet
}

func (v *NullableApiUtxoItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiUtxoItem(val *ApiUtxoItem) *NullableApiUtxoItem {
	return &NullableApiUtxoItem{value: val, isSet: true}
}

func (v NullableApiUtxoItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiUtxoItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
