/*
cardano-node-api

Cardano Node API

API version: 1.0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiResponseApiError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiResponseApiError{}

// ApiResponseApiError struct for ApiResponseApiError
type ApiResponseApiError struct {
	Msg *string `json:"msg,omitempty"`
}

// NewApiResponseApiError instantiates a new ApiResponseApiError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiResponseApiError() *ApiResponseApiError {
	this := ApiResponseApiError{}
	return &this
}

// NewApiResponseApiErrorWithDefaults instantiates a new ApiResponseApiError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiResponseApiErrorWithDefaults() *ApiResponseApiError {
	this := ApiResponseApiError{}
	return &this
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *ApiResponseApiError) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseApiError) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *ApiResponseApiError) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *ApiResponseApiError) SetMsg(v string) {
	o.Msg = &v
}

func (o ApiResponseApiError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiResponseApiError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	return toSerialize, nil
}

type NullableApiResponseApiError struct {
	value *ApiResponseApiError
	isSet bool
}

func (v NullableApiResponseApiError) Get() *ApiResponseApiError {
	return v.value
}

func (v *NullableApiResponseApiError) Set(val *ApiResponseApiError) {
	v.value = val
	v.isSet = true
}

func (v NullableApiResponseApiError) IsSet() bool {
	return v.isSet
}

func (v *NullableApiResponseApiError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiResponseApiError(val *ApiResponseApiError) *NullableApiResponseApiError {
	return &NullableApiResponseApiError{value: val, isSet: true}
}

func (v NullableApiResponseApiError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiResponseApiError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


