/*
cardano-node-api

Cardano Node API

API version: 1.0
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiResponseLocalTxMonitorSizes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiResponseLocalTxMonitorSizes{}

// ApiResponseLocalTxMonitorSizes struct for ApiResponseLocalTxMonitorSizes
type ApiResponseLocalTxMonitorSizes struct {
	Capacity *int32 `json:"capacity,omitempty"`
	Size *int32 `json:"size,omitempty"`
	TxCount *int32 `json:"tx_count,omitempty"`
}

// NewApiResponseLocalTxMonitorSizes instantiates a new ApiResponseLocalTxMonitorSizes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiResponseLocalTxMonitorSizes() *ApiResponseLocalTxMonitorSizes {
	this := ApiResponseLocalTxMonitorSizes{}
	return &this
}

// NewApiResponseLocalTxMonitorSizesWithDefaults instantiates a new ApiResponseLocalTxMonitorSizes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiResponseLocalTxMonitorSizesWithDefaults() *ApiResponseLocalTxMonitorSizes {
	this := ApiResponseLocalTxMonitorSizes{}
	return &this
}

// GetCapacity returns the Capacity field value if set, zero value otherwise.
func (o *ApiResponseLocalTxMonitorSizes) GetCapacity() int32 {
	if o == nil || IsNil(o.Capacity) {
		var ret int32
		return ret
	}
	return *o.Capacity
}

// GetCapacityOk returns a tuple with the Capacity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseLocalTxMonitorSizes) GetCapacityOk() (*int32, bool) {
	if o == nil || IsNil(o.Capacity) {
		return nil, false
	}
	return o.Capacity, true
}

// HasCapacity returns a boolean if a field has been set.
func (o *ApiResponseLocalTxMonitorSizes) HasCapacity() bool {
	if o != nil && !IsNil(o.Capacity) {
		return true
	}

	return false
}

// SetCapacity gets a reference to the given int32 and assigns it to the Capacity field.
func (o *ApiResponseLocalTxMonitorSizes) SetCapacity(v int32) {
	o.Capacity = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *ApiResponseLocalTxMonitorSizes) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseLocalTxMonitorSizes) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *ApiResponseLocalTxMonitorSizes) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *ApiResponseLocalTxMonitorSizes) SetSize(v int32) {
	o.Size = &v
}

// GetTxCount returns the TxCount field value if set, zero value otherwise.
func (o *ApiResponseLocalTxMonitorSizes) GetTxCount() int32 {
	if o == nil || IsNil(o.TxCount) {
		var ret int32
		return ret
	}
	return *o.TxCount
}

// GetTxCountOk returns a tuple with the TxCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseLocalTxMonitorSizes) GetTxCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TxCount) {
		return nil, false
	}
	return o.TxCount, true
}

// HasTxCount returns a boolean if a field has been set.
func (o *ApiResponseLocalTxMonitorSizes) HasTxCount() bool {
	if o != nil && !IsNil(o.TxCount) {
		return true
	}

	return false
}

// SetTxCount gets a reference to the given int32 and assigns it to the TxCount field.
func (o *ApiResponseLocalTxMonitorSizes) SetTxCount(v int32) {
	o.TxCount = &v
}

func (o ApiResponseLocalTxMonitorSizes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiResponseLocalTxMonitorSizes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Capacity) {
		toSerialize["capacity"] = o.Capacity
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.TxCount) {
		toSerialize["tx_count"] = o.TxCount
	}
	return toSerialize, nil
}

type NullableApiResponseLocalTxMonitorSizes struct {
	value *ApiResponseLocalTxMonitorSizes
	isSet bool
}

func (v NullableApiResponseLocalTxMonitorSizes) Get() *ApiResponseLocalTxMonitorSizes {
	return v.value
}

func (v *NullableApiResponseLocalTxMonitorSizes) Set(val *ApiResponseLocalTxMonitorSizes) {
	v.value = val
	v.isSet = true
}

func (v NullableApiResponseLocalTxMonitorSizes) IsSet() bool {
	return v.isSet
}

func (v *NullableApiResponseLocalTxMonitorSizes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiResponseLocalTxMonitorSizes(val *ApiResponseLocalTxMonitorSizes) *NullableApiResponseLocalTxMonitorSizes {
	return &NullableApiResponseLocalTxMonitorSizes{value: val, isSet: true}
}

func (v NullableApiResponseLocalTxMonitorSizes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiResponseLocalTxMonitorSizes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


